server.port=8081

spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=optimisationUsinedb;encrypt=false;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=StrongPassword123!
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.mvc.pathmatch.matching-strategy=ant_path_matcher

jwt.secret=9a4f2c8d3e1b7f6a5c4d3b2a1e0f9c8b7a6f5e4d3c2b1a0f9e8d7c6b5a4f3e2d1c0b9a8f7e6d5c4b3a2f1e0d9c8b7a6f5e4d3c2b1a0f9e8d7c6b5a4f3e2